# Generated by Django 5.2.7 on 2025-10-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30, null=True)),
                ('passport', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedServices',
            fields=[
                ('provided_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_number', models.IntegerField()),
                ('signing_date', models.DateField()),
                ('signing_place', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AOP.client')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(blank=True, null=True)),
                ('service_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AOP.clientcontract')),
                ('provided_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AOP.providedservices')),
            ],
        ),
        migrations.AddField(
            model_name='providedservices',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AOP.services'),
        ),
        migrations.AddField(
            model_name='providedservices',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AOP.suppliers'),
        ),
    ]
